version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  opencv:
    build: .
    container_name: opencv
    #command: python /code/qr_decode_video.py
    volumes:
      - /Users/king/Documents/projects/realtime_qr_decode:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
  code:
